### ISSUE TITLE
Add command fails when folder does not already exist

### ISSUE THREAD

**Issue by lucasra1** [Compile-Time/GE-Man#2]
![image](https://user-images.githubusercontent.com/17753678/165210248-d0435c5b-8d58-4440-bb10-8e02af84b54e.png)

When I manually add the folder `compatibilitytools.d` to my steam folder, the command finishes successfully

**Comment by Compile-Time** [comment]
Sorry for the inconvenience, I assumed that Steam would create the directory automatically but the README for Proton clearly states that the directory needs to be created [manually](https://github.com/ValveSoftware/Proton/#install-proton-locally).

**Comment by Compile-Time** [comment]
Hi, this is now fixed in the 0.1.1 release, therefore, I'm closing this issue.

If the new release does not fix this problem for you, please re-open the issue.

**Comment by lucasra1** [comment]
Can confirm the fix
